### PR TITLE
Fixed redirections, heredoc and open_error

### LINKED ISSUE #76: Redirections out of order

### LINKED ISSUE #83: `open_error()` shouldn't exit parent

### PR DESCRIPTION
**Pull request by mortinso**
- [x] Redirections are now done in the correct order
- [x] Heredoc runs before the replacer
- [x] `open_error` doesn't exit when it receives only one command that is a built-in 
- [x] Removed `t_content` and changed the content of `t_cmdlist` to `cmd_args`

### CODE REVIEW

**Comment by WudDoo** [comment]
Broke `$EMPTY`, now says `"command not found"`

**Comment by WudDoo** [comment]
> Broke `$EMPTY`, now says `"command not found"`

Might have to bring back the `t_content` with just the `cmd_args` inside lmao

**Comment by mortinso** [comment]
`$EMPTY` returns `"command not found"`, apparently it already did before, I don't know how to fix this issue lmao

**Comment by mortinso** [comment]
> `$EMPTY` returns `"command not found"`, apparently it already did before, I don't know how to fix this issue lmao

Since `env_var()` removes quotes, there's no way to diferentiate between `""`/`''` and `$EMPTY` because they all get replaced with `NULL`.
* `''`/`""` should return `"command not found"`
* `$EMPTY` should just give a new prompt

**Pull request merged**
